### ISSUE TITLE
calculation of the generalized_average_precision

### ISSUE THREAD

**Issue by gmichalo** [orenmel/lexsub#8]
In the code of (https://github.com/orenmel/lexsub/blob/master/jcs/evaluation/measures/generalized_average_precision.py )it seems that for the calculation of the  **nominator** of the  generalized_average_precision (gap) score the weights (gold_score) from the   gold_vector are used. However, in the paper(http://aclweb.org/anthology//P/P10/P10-1097.pdf) only the **denominator** uses the weights(gold_score), and the **nominator** only uses the p_i variable which was defined in the previous equation and it does not use the weights. 

Could you clarify if you are using the equation for the gap from the http://aclweb.org/anthology//P/P10/P10-1097.pdf or did you change the way that gap score is calculated?

**Comment by orenmelamud** [comment]
Note the phrasing in the reference paper:
"If we take x_i to be the gold standard weight of the i-th item or zero if it is not in the gold standard, we can define generalized average precision as follows:". 
I believe this applies to all x, including x_k in the p_i formula. That makes most sense and also although it's been a while since I did this work, I do remember looking up at least one more reference for this GAP measure.

**Comment by gmichalo** [comment]
Thank you for your reply. Now, that I read more closely the sentence that you provided I think the formula should be as you wrote it (I also thought that it made more sense this way but i just wanted to be sure).
